import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import yaml from 'js-yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

function parseCSV(csvContent) {
  const lines = csvContent.trim().split('\n');
  if (lines.length === 0) {
    throw new Error('CSV file is empty');
  }
  
  // Parse header
  const headers = lines[0].split(',').map(h => h.trim());
  
  // Parse data rows
  const users = [];
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue; // Skip empty lines
    
    // Simple CSV parsing (handles quoted values)
    const values = [];
    let currentValue = '';
    let inQuotes = false;
    
    for (let j = 0; j < line.length; j++) {
      const char = line[j];
      
      if (char === '"') {
        inQuotes = !inQuotes;
      } else if (char === ',' && !inQuotes) {
        values.push(currentValue.trim());
        currentValue = '';
      } else {
        currentValue += char;
      }
    }
    values.push(currentValue.trim()); // Add last value
    
    // Create user object
    const user = {};
    headers.forEach((header, index) => {
      const value = values[index] || '';
      // Only add non-empty values
      if (value) {
        user[header] = value;
      }
    });
    
    // Only add user if it has at least a firstName
    if (user.firstName) {
      users.push(user);
    }
  }
  
  return users;
}

function convertToYAMLFormat(users) {
  return users.map(user => {
    const yamlUser = {
      firstName: user.firstName
    };
    
    // Add optional fields only if they exist
    if (user.lastName) {
      yamlUser.lastName = user.lastName;
    }
    
    if (user.gender) {
      yamlUser.gender = user.gender;
    }
    
    if (user.birthdate) {
      // Ensure birthdate is in MM/DD/YYYY format
      yamlUser.birthdate = user.birthdate;
    }
    
    // Tags are not in CSV, so we'll leave them out
    // If you want to add default tags, you can do it here
    
    return yamlUser;
  });
}

function convertCSVToYAML(csvFilePath, outputYamlPath) {
  try {
    console.log(`Reading CSV file: ${csvFilePath}`);
    const csvContent = readFileSync(csvFilePath, 'utf-8');
    
    console.log('Parsing CSV...');
    const users = parseCSV(csvContent);
    console.log(`Found ${users.length} users in CSV.\n`);
    
    console.log('Converting to YAML format...');
    const yamlUsers = convertToYAMLFormat(users);
    
    // Convert to YAML string
    const yamlContent = yaml.dump(yamlUsers, {
      indent: 2,
      lineWidth: -1, // No line width limit
      quotingType: '"',
      forceQuotes: false
    });
    
    // Add header comment
    const headerComment = `# Converted from CSV file
# Generated by: scripts/csv-to-yaml.js
# 
# Required fields:
#   - firstName: (string) User's first name
#
# Optional fields:
#   - lastName: (string) User's last name
#   - gender: (string) One of: "Male", "Female", "Non-Binary"
#   - birthdate: (string) Format: MM/DD/YYYY (e.g., "01/15/2000")
#   - tags: (array of strings) Tags to associate with the user
#
# Usage:
#   node scripts/upload-users.js ${outputYamlPath}

`;
    
    const finalYaml = headerComment + yamlContent;
    
    console.log(`Writing YAML file: ${outputYamlPath}`);
    writeFileSync(outputYamlPath, finalYaml, 'utf-8');
    
    console.log(`\n✅ Conversion completed successfully!`);
    console.log(`   Converted ${yamlUsers.length} users`);
    console.log(`   Output file: ${outputYamlPath}`);
    console.log(`\nNext step: Run the upload script:`);
    console.log(`   npm run upload:users ${outputYamlPath}`);
    
  } catch (error) {
    console.error('❌ Conversion failed:', error);
    process.exit(1);
  }
}

// Get file paths from command line arguments
const csvFilePath = process.argv[2];
const outputYamlPath = process.argv[3];

if (!csvFilePath) {
  console.error('❌ Error: Please provide a CSV file path');
  console.error('Usage: node scripts/csv-to-yaml.js <input-csv-file> [output-yaml-file]');
  console.error('Example: node scripts/csv-to-yaml.js data/noco_users.csv data/users.yaml');
  console.error('\nIf output file is not specified, it will default to <input-file>.yaml');
  process.exit(1);
}

// If output path not provided, use input filename with .yaml extension
const finalOutputPath = outputYamlPath || csvFilePath.replace(/\.csv$/i, '.yaml');

convertCSVToYAML(csvFilePath, finalOutputPath);
